### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by ppoetsma** [JelteMX/mendix-json-widget#2]
Hi,

When the attribute that contains the JSON string is empty then this error is shown to the user:

> SyntaxError: Unexpected end of JSON input

I would be great if the widget handles this.

Regards,
Paul

**Comment by JelteMX** [comment]
Version [1.1.1](https://github.com/JelteMX/mendix-json-widget/releases/tag/1.1.1) fixes this issue. If it has an empty string, it will not show the widget at all. Published in the AppStore

**Comment by ppoetsma** [comment]
Thanks!
