### ISSUE TITLE
The 'offlineCapable' attribute is not declared.

### ISSUE THREAD

**Issue by ppoetsma** [JelteMX/mendix-json-widget#4]
Hi Jelte,

When installing widget version 1.1.1 in Modeler 5.21.1.1 I get this error:

```
Package 'C:\...\widgets\JSON.mpk': Widget XML file 'JSON/Editor.xml' does not conform to the XML schema:
The 'offlineCapable' attribute is not declared.
```

I removed that from Editor.xml and then the modeler accepts the widget. However at runtime I get this in the web UI:

```
No constructor found for widget JSON.widget.Editor
```

Regards,
Paul

**Comment by JelteMX** [comment]
My bad, this only works in [Mendix 5.21.5 and upwards](https://docs.mendix.com/releasenotes/desktop-modeler/5.21#5-21-5-a-name-5215-a)
