### ISSUE TITLE
No constructor found for widget JSON.widget.Editor Mx 7.23

### ISSUE THREAD

**Issue by ssuijkerbuijk** [JelteMX/mendix-json-widget#6]
Getting te following error in MX 7.23:

No constructor found for widget JSON.widget.Editor

MX console says:

factoryThrew Error: factoryThrew
at l (http://localhost:8080/mxclientsystem/mxui/mxui.js?636858170571227361:5:426)
at http://localhost:8080/mxclientsystem/mxui/mxui.js?636858170571227361:5:9149
at Ve (http://localhost:8080/mxclientsystem/mxui/mxui.js?636858170571227361:5:9258)
at Ve (http://localhost:8080/mxclientsystem/mxui/mxui.js?636858170571227361:5:8894)
at Ve (http://localhost:8080/mxclientsystem/mxui/mxui.js?636858170571227361:5:8894)
at http://localhost:8080/mxclientsystem/mxui/mxui.js?636858170571227361:5:9448
at He (http://localhost:8080/mxclientsystem/mxui/mxui.js?636858170571227361:5:9316)
at We (http://localhost:8080/mxclientsystem/mxui/mxui.js?636858170571227361:5:9388)
at r (http://localhost:8080/mxclientsystem/mxui/mxui.js?636858170571227361:5:10574)
at HTMLScriptElement. (http://localhost:8080/mxclientsystem/mxui/mxui.js?636858170571227361:5:12797)

and

Loading module JSON/widget/Editor failed! Check script file for syntax errors.

**Comment by JelteMX** [comment]
Oh boy... I hope they didn't break something in the new MX version. I will check it out.

**Comment by JelteMX** [comment]
I have tested this locally, should work fine with MX 7.23. How are you using this widget? Is this in a tab container, maybe using conditional visibility? Please let me know the circumstances where this error occurs.

**Comment by ssuijkerbuijk** [comment]
Weird. Have just a simple setup here. Page with a dataview(page parameter) showing a comitted object.
Tried some different settings for the widget without any luck.

**Comment by ssuijkerbuijk** [comment]
See attached file for an 7.23 example project with the error.
[TESTJson.zip](https://github.com/JelteMX/mendix-json-widget/files/2881462/TESTJson.zip)

**Comment by JelteMX** [comment]
Thanks, I'll take a look at it

**Comment by JelteMX** [comment]
Stupid... I thought I fixed the issue in the previous version. Turns out I forgot something. Anyway, thanks for reporting it. I have released version [1.1.2](https://github.com/JelteMX/mendix-json-widget/releases/tag/1.1.2) in the App Store, that should fix your issue :-)

**Comment by PincerKrister** [comment]
Hey, I'm getting the same error in 6.10.3 with widget version 1.1.1, can you help figure this out or am I doing something wrong?

**Comment by JelteMX** [comment]
@PincerKrister you are using an old version. Version 1.3.0 is the latest in the App Store. Please update to the latest version and see if that fixes the issue

**Comment by PincerKrister** [comment]
Unfortunately my project is still using 6.x modeler version and we won't upgrade until later this year. But I like your widget very much so, I was hoping if you could point me in the direction to correct the regenerator error. If it is too much of an effort then I will wait until we get time to upgrade our project and use 1.3.0.

**Comment by JelteMX** [comment]
@PincerKrister it should work with MX6, but I see we updated the AppStore to say you need MX7 for this. What you could do is just download the **JSON.mpk** from [here](https://github.com/JelteMX/mendix-json-widget/releases/tag/1.3.0) and replace the one in your project/widgets folder with that one. See if it works

**Comment by PincerKrister** [comment]
@JelteMX Thank you this worked for me!
